# Site settings
title: "李亚平"
description: "明明知道公司资不抵债，无法正常支付工资的情况下，还不断招聘新人，一边骗取上游厂家的SDK，一边压迫员工在第一个月发工资前做完一个产品，"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: dog.jpg
hero-title: "李亚平的传奇人生"
hero-description: "骗厂家，骗员工，骗合作伙伴，骗政府的奖金，一起关注狗子的吹牛本事！"

# Author - Creator
author-name: "狗子 李亚平"
author-image: 10.jpg
about-author: "明明知道公司资不抵债，无法正常支付工资的情况下，还不断招聘新人，一边骗取上游厂家的SDK，一边压迫员工在第一个月发工资前做完一个产品，"
author-email: dog.liyaping@outlook.com
author-twitter: https://twitter.com/
author-facebook: https://twitter.com/
author-instagram: https://www.instagram.com/
author-pinterest: https://pinterest.com/

# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  Natali_Braxton:
    author-name: Natali Braxton
    author-image: 111.jpg
    about-author: My name is Natali Braxton. I love walking, I play the guitar in my spare time. And also write articles about different technologies.
    author-email: dog.liyaping@outlook.com
    author-twitter: https://twitter.com/
    author-facebook: https://twitter.com/
    author-instagram: https://www.instagram.com/
    author-pinterest: https://pinterest.com/

# Social Media Links (Links are located in hero and footer)
twitter: https://twitter.com/
facebook: https://facebook.com/
google-plus: https://plus.google.com/
instagram: https://www.instagram.com/
pinterest: https://pinterest.com/
youtube: https://www.youtube.com/

# Contact Form Settings
contact-subtitle: '如果李亚平欠了你的钱，请提供金额和判决书，任何第三方证明的证据都可以，然后会在本网站上列出来。' # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "github.us13.list-manage.com/subscribe/post?u=03af2c985f210063fc6ef615e&amp;id=c8d729adf3" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
 - node_modules
